version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
init:
- cmd: 
before_build:
- cmd: >-
    git submodule update --init --recursive

    dotnet restore

    nuget restore

    cinst WinPcap
build:
  project: SharpPcap.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal